import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  greeting: "Hello. Hamba will help you navigate in your wheelchair today.",
  instructions: "Welcome to Hamba. Top button records your path. Middle button follows a saved route. Bottom button reports obstacles. Large center button checks accessibility using AI.",
  recordRoute: "Record Route",
  followRoute: "Follow Route",
  reportHazard: "Report Obstacle",
  describeScene: "Check Accessibility",
  startRecording: "Start Recording",
  stopRecording: "Stop Recording",
  dropWaypoint: "Drop Waypoint",
  saveRoute: "Save Route",
  cancel: "Cancel",
  hazardReported: "Obstacle reported successfully.",
  hazardWarning: "Warning: Obstacle nearby.",
  waypointReached: "Waypoint reached.",
  selectRoute: "Select a Route",
  noRoutes: "No routes saved yet.",
  back: "Go Back",
  analyzing: "Analyzing accessibility...",
  guardianMode: "Guardian Mode",
  trafficWarning: "Warning: High traffic area.",
  approachingIntersection: "Approaching a busy intersection. Please be careful.",
  dangerDetected: "Obstacle detected!",
  smartCaneMode: "Smart Cane Mode",
  smartCaneActive: "Smart Cane Mode Active.",
  // Wheelchair specific
  steps: "Steps or Stairs",
  noRamp: "No Ramp",
  narrowPath: "Path Too Narrow",
  tooSteep: "Too Steep",
  brokenPavement: "Broken Pavement",
  noCurbCut: "No Curb Cut",
  brokenElevator: "Broken Elevator",
  accessible: "Accessible",
  obstacleMapped: "Obstacle mapped. Describe it now.",
  communityObstacles: "Community Obstacles",
  wheelchairNavigator: "Wheelchair Navigator",
  descriptionPrompt: "Please describe the obstacle.",
  routeNamePrompt: "What should we name this route?",
  // Creative features
  checkSlope: "Check Slope",
  checkDoorway: "Check Doorway",
  slopeAnalysis: "Analyzing slope steepness...",
  doorwayAnalysis: "Checking doorway width...",
  restroomSearch: "Find Accessible Restroom",
  surfaceTexture: "Surface Texture",
};
